- app/models/article.rb
- db/migrate/20240914174342_create_articles.rb
- db/schema.rb
- test/fixtures/articles.yml
- test/models/article_test.rb
#11
- 5 https://guides.rubyonrails.org/autoloading_and_reloading_constants.html
- 6 https://en.wikipedia.org/wiki/Model–view–controller
- 6.1 A model is a Ruby class that is used to represent data. Additionally, models can interact with the application's database through a feature of Rails called Active Record.
> autoloading

- .gitignore
- Gemfile
- Gemfile.lock
- Procfile.dev
- README.md
- app/assets/config/manifest.js
- app/assets/stylesheets/application.tailwind.css
- app/views/articles/show.html.erb
- app/views/layouts/application.html.erb
- bin/dev
- config/tailwind.config.js
#15
notes
- prompt - how to add tailwind to rails
- `bin/dev` instead of `bin/rails s`
sources
https://stackoverflow.com/questions/74642453/how-can-i-update-tailwind-without-having-to-precompile-assets-every-time-rails
> tailwind 🎭💎

- app/views/layouts/_footer.html.erb
- app/views/layouts/application.html.erb
> add footer

- app/controllers/api/api_controller.rb
- app/controllers/api/articles_controller.rb
- app/controllers/api_controller.rb
- config/routes.rb
> articles GET api

- app/models/user.rb
- db/migrate/20240928200342_create_users.rb
- db/schema.rb
- docs/rails-commands.md
- test/fixtures/users.yml
- test/models/user_test.rb
#47
This pull request introduces a `User` model to the application, with corresponding migrations and test cases.
1. **User Model (`app/models/user.rb`)**
- Created a simple `User` model to handle user data.
2. **Migration (`db/migrate/.._create_users.rb`)**
- Added a migration to create the `users` table with the following attributes:
- `name`: string
- `email`: string
- `timestamps`: included for record tracking.
3. **Schema Update (`db/schema.rb`)**
- Updated the schema file to reflect the new `users` table.
4. **Test Fixtures (`test/fixtures/users.yml`)**
- Added fixture data for the `User` model for use in tests.
5. **Test Cases (`test/models/user_test.rb`)**
- Created a basic test file for the `User` model. Currently includes placeholder tests.
6. **Documentation Update …
> user model

- app/controllers/articles_controller.rb
> protect route

- app/models/article.rb
- app/views/articles/show.html.erb
> playing around 3

- Gemfile
- Gemfile.lock
- docs/rails-commands.md
- test/controllers/posts_controller_test.rb
- test/fixtures/users.yml
- test/models/user_test.rb
#70
later
```bash
drewapp on  minitest [$] via  v22.5.1 via 💎 v3.2.1 took 2s 
❯ rails test         
Rebuilding...
Done in 255ms.
Running 4 tests in a single process (parallelization threshold is 50)
Run options: --seed 23243
....
Finished in 7.302744s, 0.5477 runs/s, 0.6847 assertions/s.
4 runs, 5 assertions, 0 failures, 0 errors, 0 skips
```
> add minitest

- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/views/chats/new.html.erb
> style chat response

- app/controllers/chats_controller.rb
- config/routes.rb
#82
- Which is Better?
- Controller-based authentication (before_action :authenticate_user!) is more flexible and keeps your routes file clean. It allows you to enforce authentication on specific actions and handle exceptions more gracefully.
- Route-based authentication (authenticate :user do ... end) is more explicit and ensures that all routes in that block are protected, but it’s less flexible and can clutter your routing file if overused.
> auth users for chat

- .gitignore
- app/controllers/chats_controller.rb
- app/services/openai_service.rb
#85
#80
---
Notes
Post/Redirect/Get (PRG) pattern, [SO](https://stackoverflow.com/questions/10827242/understanding-the-post-redirect-get-pattern)
> bug chats get route

- app/views/articles/index.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/_navbar.html.erb
- docs/rails-commands.md
> frontend: add login to nav

- app/controllers/chats_controller.rb
- app/views/chats/new.html.erb
> backend: update ai model

- app/helpers/application_helper.rb
- app/views/layouts/_navbar.html.erb
- app/views/layouts/application.html.erb
- docs/rails-commands.md
- test/controllers/chats_controller_test.rb
- test/system/user_signup_test.rb
- test/test_helper.rb
#96
```bash
Done in 278ms.
Running 2 tests in a single process (parallelization threshold is 50)
Run options: --seed 12788
Capybara starting Puma...
* Version 6.4.3, codename: The Eagle of Durango
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:50427
..
Finished in 6.694706s, 0.2987 runs/s, 0.5975 assertions/s.
2 runs, 4 assertions, 0 failures, 0 errors, 0 skips
```
> test: signup test

- app/views/shared/_error_messages.html.erb
- test/system/user_login_test.rb
> test: write login test

- app/controllers/articles_controller.rb
- app/models/article.rb
- app/models/user.rb
- app/views/articles/show.html.erb
- db/migrate/20241008032623_add_user_id_to_articles.rb
- db/schema.rb
> backend: prevent unauthorized deletions

- app/controllers/articles_controller.rb
- db/migrate/20241008032623_add_user_id_to_articles.rb
- db/migrate/20241008174342_create_articles.rb
- db/schema.rb
- docs/rails-commands.md
- test/controllers/articles_controller_test.rb
#113
```bash
drewapp on  show-articles [$!+] via  v22.5.1 via 💎 v3.2.1 took 13s 
❯ rails test test/controllers/articles_controller_test.rb
bin/rails aborted!
ActiveRecord::EnvironmentMismatchError: You are attempting to modify a database that was last run in `development` environment. (ActiveRecord::EnvironmentMismatchError)
You are running in `test` environment. If you are sure you want to continue, first set the environment using:
bin/rails db:environment:set RAILS_ENV=test
Tasks: TOP => db:test:load_schema => db:test:purge => db:check_protected_environments
(See full trace by running task with --trace)
Running 1 tests in a single process (parallelization threshold is 50)
Run options: --seed 964
.
Finished in 5.312655s, 0.1882 runs/s, 0.3765 assertions/s.
1 runs, 2 assertions, 0 …
```
> full-stack: allow public view of articles

- app/views/layouts/_navbar.html.erb
- app/views/layouts/_navbar_links.html.erb
- app/views/layouts/application.html.erb
> 🐞: fix nav new link (mobile)

- docs/rails-commands.md
updating `rails-commands` docs to be more readable
> docs: update rails-commands

- app/controllers/chats_controller.rb
- app/views/chats/_chat_response.html.erb
- app/views/chats/create.turbo_stream.erb
- app/views/chats/new.html.erb
#144 
- improve chat UX
https://turbo.hotwired.dev/handbook/streams
> turbo chat
